# yaml-language-server: $schema=mcux_doc_config_schema.json
project: mcuxsdk
copyright: '2024, NXP'
author: 'NXP'
extensions:
- sphinx_rtd_theme
- sphinx.ext.extlinks
- vcs_link
- sphinx.ext.todo
- sphinx.ext.extlinks
- myst_parser
- external_content
- page_filter
- sphinx.ext.graphviz
- sphinx_tabs.tabs
- sphinxmermaid
source_suffix:
  .rst: restructuredtext
  .readme: markdown
  .md: markdown
ext_doxygen:
  doxyfile: docs/drivers/Doxyfile_lib_PDF_RM_Drivers
  fmt: True
  fmt_vars: {}
vcs_link:
- pattern: ".*"
  replace_prefix: ""
  link: "https://github.com/nxp-mcuxpresso/mcuxsdk-doc"
external_contents:
- root: 'docs'
  pattern: 'index.rst'
- root: 'docs'
  pattern: 'middleware/index.rst'
- root: 'docs'
  pattern: 'middleware/audio_voice/maestro/*'
- root: 'docs'
  pattern: 'middleware/audio_voice/components/*'
- root: 'docs'
  pattern: 'middleware/aws_iot/*'
- root: 'docs'
  pattern: 'middleware/multicore/*'
- root: 'docs'
  pattern: 'middleware/freemaster/*'
- root: 'docs'
  pattern: 'middleware/lwip/*'
- root: 'docs'
  pattern: 'middleware/lvgl/index.rst'
- root: docs
  pattern: 'generation.rst'
- root: docs
  pattern: 'develop/document/*'
- root: docs
  pattern: 'rtos/index.rst'
- root: docs
  pattern: 'rtos/*'
- root: 'docs'
  pattern: 'middleware/fatfs/*'
modules:
  introduction:
    default: True
    external_contents:
    - root: 'docs'
      pattern: 'introduction/*'
  gsd:
    default: True
    external_contents:
    - root: 'docs'
      pattern: 'gsd/*'
    internal:
      external_contents:
      - root: ..
        pattern: bifrost/readme.md
  doxygen:
    default: false
    extensions:
    - breathe
    - doxyrunner
  boards:
    default: True
    external_contents:
    - root: docs
      pattern: 'boards/*'
  drivers:
    default: True
    external_contents:
    - root: 'docs'
      pattern: 'drivers/*'
  release:
    default: True
    external_contents:
    - root: 'docs'
      pattern: 'release/*'
  examples:
    default: True
    external_contents:
    - root: .
      pattern: 'examples/**/*.md'
    - root: .
      pattern: 'examples/**/*.jpg'
    - root: .
      pattern: 'examples/**/*.png'
    - root: .
      pattern: 'examples/**/index.rst'
    vcs_link:
    - pattern: examples/.*\.md
      replace_prefix: "examples/"
      link: "https://github.com/nxp-mcuxpresso/mcuxsdk-examples/"
    - pattern: examples/.*\.rst
      replace_prefix: "examples/"
      link: "https://github.com/nxp-mcuxpresso/mcuxsdk-examples/"
  contribute:
    default: True
    external_contents:
    - root: 'docs'
      pattern: 'contribute/*'
  bifrost:
    default: True
    external_contents:
    - root: '..'
      pattern: 'bifrost/readme.md'
  dev_architect:
    default: True
    external_contents:
    - root: 'docs'
      pattern: 'develop/architect.md'
  dev_sdk:
    default: True
    external_contents:
      - root: 'docs'
        pattern: 'develop/sdk/*'
  dev_build_system:
    default: True
    external_contents:
    - root: 'docs'
      pattern: 'develop/build_system/*'
    internal:
      external_contents:
      - root: '.'
        pattern: 'ecosystem/sdk_generator/doc_ecosystem/index.rst'
      - root: '.'
        pattern: 'ecosystem/sdk_generator/doc_ecosystem/*'
  dev_document:
    default: True
    external_contents:
    - root: 'docs'
      pattern: 'develop/document/*'
  mid_aws_iot:
    default: true
    external_contents:
    - root: .
      pattern: 'middleware/aws_iot/device-shadow/README.md'
    - root: .
      pattern: 'middleware/aws_iot/device-defender/README.md'
    - root: .
      pattern: 'middleware/aws_iot/jobs/README.md'
    - root: .
      pattern: 'middleware/aws_iot/ota/README.md'
  mid_wireless_fwk:
    default: true
    external_contents:
    - root: .
      pattern: 'middleware/wireless/framework/index.rst'
    - root: .
      pattern: 'middleware/wireless/framework/*.md'
    - root: .
      pattern: 'middleware/wireless/framework/**/*.md'
    - root: .
      pattern: 'middleware/wireless/framework/**/*.PNG'
  mid_lwip:
    default: true
    external_contents:
    - root: .
      pattern: 'middleware/lwip/ChangeLogKSDK.txt'
    - root: .
      pattern: 'middleware/lwip/port/README.md'
  mid_lvgl:
    default: true
    external_contents:
    - root: .
      pattern: 'middleware/lvgl/docs/integration/chip/nxp.rst'
  mid_wifi_nxp:
    default: true
    external_contents:
    - root: .
      pattern: 'middleware/wifi_nxp/docs/*'
  mid_maestro:
    default: true
    external_contents:
    - root: .
      pattern: 'middleware/audio_voice/maestro/*.md'
    - root: .
      pattern: 'middleware/audio_voice/maestro/doxygen/*'
    - root: .
      pattern: 'middleware/audio_voice/maestro/zephyr/README.rst'
    - root: .
      pattern: 'middleware/audio_voice/maestro/zephyr/samples/record_ram/README.rst'
    - root: .
      pattern: 'middleware/audio_voice/maestro/zephyr/samples/record_vit/README.rst'
    - root: .
      pattern: 'middleware/audio_voice/maestro/zephyr/tests/encoder/README.rst'
    - root: .
      pattern: 'middleware/audio_voice/maestro/zephyr/tests/memToMem/README.rst'
    - root: .
      pattern: 'middleware/audio_voice/maestro/zephyr/tests/decoder/README.rst'
  mid_avc:
    default: true
    external_contents:
    - root: .
      pattern: 'middleware/audio_voice/components/README.md'
    - root: .
      pattern: 'middleware/audio_voice/components/ssrc/doc/topics/*.md'
    - root: .
      pattern: 'middleware/audio_voice/components/ssrc/doc/*.md'
    - root: .
      pattern: 'middleware/audio_voice/components/decoders/aac/doc/*.md'
    - root: .
      pattern: 'middleware/audio_voice/components/decoders/flac/doc/*.md'
    - root: .
      pattern: 'middleware/audio_voice/components/decoders/mp3/doc/*.md'
    - root: .
      pattern: 'middleware/audio_voice/components/decoders/wav/doc/*.md'
  mid_multicore:
    default: true
    external_contents:
    - root: .
      pattern: 'middleware/multicore/*.md'
    - root: .
      pattern: 'middleware/multicore/mcuxsdk-doc/MCSDK_ReleaseNotes/*.md'
    - root: .
      pattern: 'middleware/multicore/mcuxsdk-doc/MCSDK_ReleaseNotes/topics/*.md'
    - root: .
      pattern: 'middleware/multicore/mcuxsdk-doc/MCSDK_GettingStarted/*.md'
    - root: .
      pattern: 'middleware/multicore/mcuxsdk-doc/MCSDK_GettingStarted/topics/*.md'
    - root: .
      pattern: 'middleware/multicore/mcuxsdk-doc/MCSDK_GettingStarted/images/*.*'
    - root: .
      pattern: 'middleware/multicore/mcuxsdk-doc/eRPC_GettingStarted/*.md'
    - root: .
      pattern: 'middleware/multicore/mcuxsdk-doc/eRPC_GettingStarted/topics/*.md'
    - root: .
      pattern: 'middleware/multicore/mcuxsdk-doc/eRPC_GettingStarted/images/*.*'
    - root: .
      pattern: 'middleware/multicore/rpmsg-lite/*.md'
    - root: .
      pattern: 'middleware/multicore/rpmsg-lite/doxygen/*'
    - root: .
      pattern: 'middleware/multicore/mcmgr/*.md'
    - root: .
      pattern: 'middleware/multicore/mcmgr/doc/*'
    - root: .
      pattern: 'middleware/multicore/mcmgr/doxygen/*'
    - root: .
      pattern: 'middleware/multicore/erpc/*.md'
    - root: .
      pattern: 'middleware/multicore/erpc/doxygen/*'
  mid_mcuboot:
    default: true
    external_contents:
    - root: .
      pattern: 'middleware/mcuboot_opensource/docs/*.md'
    vcs_link:
    - pattern: "middleware/mcuboot_opensource/.*md"
      replace_prefix: "middleware/mcuboot_opensource/"
      link: "https://github.com/nxp-mcuxpresso/mcuboot_opensource/"
  mid_freertos_drivers:
    default: true
    external_contents:
    - root: .
      pattern: 'rtos/freertos/freertos-drivers/README.md'
    - root: .
      pattern: 'rtos/freertos/freertos-drivers/CHANGELOG.md'
  rtos_freertos:
    default: true
    external_contents:
    - root: .
      pattern: 'rtos/freertos/freertos-kernel/README.md'
    - root: .
      pattern: 'rtos/freertos/freertos-kernel/README_mcuxsdk.md'
    - root: .
      pattern: 'rtos/freertos/freertos-kernel/CHANGELOG_mcuxsdk.md'
    - root: .
      pattern: 'rtos/freertos/freertos-kernel/mcuxsdk-doc/*.*'
    - root: .
      pattern: 'rtos/freertos/backoffalgorithm/README.md'
    - root: .
      pattern: 'rtos/freertos/corehttp/README.md'
    - root: .
      pattern: 'rtos/freertos/corejson/README.md'
    - root: .
      pattern: 'rtos/freertos/coremqtt/README.md'
    - root: .
      pattern: 'rtos/freertos/coremqtt-agent/README.md'
    - root: .
      pattern: 'rtos/freertos/corepkcs11/README.md'
    - root: .
      pattern: 'rtos/freertos/freertos-plus-tcp/README.md'
  mid_fatfs:
    default: true
    external_contents:
    - root: .
      pattern: 'middleware/fatfs/*'
  mid_freemaster:
    default: true
    external_contents:
    - root: .
      pattern: 'middleware/freemaster/doc/index.md'
    - root: .
      pattern: 'middleware/freemaster/doc/user_guide/*'
  mid_issdk:
    default: true
    external_contents:
    - root: 'docs'
      pattern: 'middleware/issdk/*'
  mid_ble:
    default: true
    external_contents:
    - root: 'docs'
      pattern: 'middleware/wireless/Bluetooth/*'
  mid_usb:
    default: true
    external_contents:
    - root: .
      pattern: 'middleware/usb/docs/*'
  mid_edgefast_bluetooth:
    default: true
    external_contents:
    - root: .
      pattern: 'middleware/edgefast_bluetooth/docs/*'
